# Version 1 specific configuration
v2:
  replicaCount: 1
  image:
    name: booking-service
    tag: latest
    pullPolicy: IfNotPresent
  labels:
    version: v2
  env:
    - name: ENABLE_FEATURE_X
      value: "true"
    - name: PONG_STRING
      value: "pong-v2"